const KEY='meu-controlo-pwa-v1';
const seed={locations:[{id:'atl',name:'Banco Atlantico',type:'Banco'},{id:'mao',name:'Em mao',type:'Numerario'}],subs:[{id:'renda',name:'Renda',note:'Reserva para habitacao'},{id:'formacao',name:'Formacao',note:'Cursos e certificacoes'},{id:'lazer',name:'Lazer',note:'Entretenimento'},{id:'gastos',name:'Gastos gerais',note:'Dia a dia'}],people:[{id:'mena',name:'Mena',note:'Dinheiro sob responsabilidade'},{id:'nina',name:'Nina',note:'Dinheiro sob responsabilidade'}],moves:[{id:'1',owner:'personal',subId:'gastos',type:'in',amount:650000,date:'2026-10-01',desc:'Salario',locationId:'atl'},{id:'2',owner:'third',personId:'mena',type:'in',amount:250000,date:'2026-10-01',desc:'Valor recebido',locationId:'atl'},{id:'3',owner:'third',personId:'nina',type:'in',amount:180000,date:'2026-10-01',desc:'Valor recebido',locationId:'mao'}],debts:[]};
let data=load(),view='dashboard',drill=null,deferredPrompt=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
const id=()=>crypto.randomUUID();
const kz=v=>new Intl.NumberFormat('pt-AO',{style:'currency',currency:'AOA',maximumFractionDigits:0}).format(Number(v||0)).replace('AOA','Kz');
const signed=m=>m.type==='in'?Number(m.amount):-Number(m.amount);
const locName=x=>data.locations.find(l=>l.id===x)?.name||'Local removido';
const subName=x=>data.subs.find(s=>s.id===x)?.name||'Subconta removida';
const personalMoves=()=>data.moves.filter(m=>m.owner==='personal');
const personalBalance=()=>personalMoves().reduce((s,m)=>s+signed(m),0);
const thirdBalance=p=>data.moves.filter(m=>m.owner==='third'&&m.personId===p).reduce((s,m)=>s+signed(m),0);
const loanDue=p=>data.moves.filter(m=>m.owner==='third'&&m.personId===p&&m.type==='loan').reduce((s,m)=>s+Math.max(0,m.amount-(m.received||0)),0);
const locationTotal=l=>data.moves.filter(m=>m.locationId===l).reduce((s,m)=>s+signed(m),0);
const subBalance=s=>personalMoves().filter(m=>m.subId===s).reduce((a,m)=>a+signed(m),0);
function nav(){return [['dashboard','Visao geral'],['personal','Meu dinheiro'],['debts','Dividas'],['third','Dinheiro de outrem'],['locations','Locais']].map(([v,l])=>`<button data-nav="${v}" class="${view===v?'active':''}">${l}</button>`).join('')}
function shell(content){document.querySelector('#app').innerHTML=`<div class="app"><header class="top"><small>CONTROLO FINANCEIRO</small><h1>Meu Controlo</h1><div class="toolbar"><button class="btn soft" id="installBtn">Instalar aplicacao</button><button class="btn dark" id="exportBtn">Exportar backup</button><label class="btn dark">Importar backup<input id="importFile" type="file" accept="application/json" hidden></label></div></header><nav class="nav">${nav()}</nav><main class="container">${content}</main></div>`;bindGlobal()}
function render(){if(view==='dashboard')dashboard();if(view==='personal')personal();if(view==='debts')debts();if(view==='third')third();if(view==='locations')locations()}
function dashboard(){const third=data.people.reduce((s,p)=>s+thirdBalance(p.id),0),receivable=data.people.reduce((s,p)=>s+loanDue(p.id),0),owed=data.debts.filter(d=>d.direction==='pay').reduce((s,d)=>s+d.total-d.paid,0);shell(`<section class="hero"><div class="muted" style="color:#a7f3d0">Meu dinheiro disponivel</div><div class="big">${kz(personalBalance())}</div><div>Valores de terceiros permanecem separados.</div></section><div class="grid">${stat('Meu dinheiro',personalBalance(),'green')}${stat('Dinheiro de outrem',third,'blue')}${stat('Emprestimos a receber',receivable,'amber')}${stat('Minhas dividas',owed,'red')}</div><div class="section-head"><div><h2>Onde esta todo o dinheiro?</h2><div class="muted">Clique num local para ver quem possui dinheiro e quanto.</div></div></div><div class="grid">${data.locations.map(l=>`<article class="card click" data-open-location="${l.id}"><div class="muted">${l.type}</div><h3>${esc(l.name)}</h3><div class="money blue">${kz(locationTotal(l.id))}</div></article>`).join('')||empty('Crie o primeiro local.')}</div>`);document.querySelectorAll('[data-open-location]').forEach(x=>x.onclick=()=>{view='locations';drill=x.dataset.openLocation;render()})}
function stat(l,v,c){return `<article class="card"><div class="muted">${l}</div><div class="money ${c}">${kz(v)}</div></article>`}
function personal(){if(drill){const sub=data.subs.find(s=>s.id===drill),moves=personalMoves().filter(m=>m.subId===drill);shell(`<button class="btn dark" id="back">Voltar</button><section class="hero"><div>${esc(sub?.name||'Subconta')}</div><div class="big">${kz(subBalance(drill))}</div></section><div class="section-head"><h2>Movimentos</h2><button class="btn primary" id="addPersonal">Adicionar</button></div>${movementList(moves)}`);document.querySelector('#back').onclick=()=>{drill=null;render()};document.querySelector('#addPersonal').onclick=()=>personalModal(drill);bindRows();return}shell(`<div class="section-head"><div><h2>Minhas subcontas</h2><div class="muted">Finalidades criadas por si.</div></div><div><button class="btn dark" id="addSub">Nova subconta</button> <button class="btn primary" id="addPersonal">Movimento</button></div></div><div class="grid">${data.subs.map(s=>`<article class="card click" data-sub="${s.id}"><div class="muted">${esc(s.note||'')}</div><h3>${esc(s.name)}</h3><div class="money green">${kz(subBalance(s.id))}</div></article>`).join('')||empty('Crie a primeira subconta.')}</div>`);document.querySelector('#addSub').onclick=subModal;document.querySelector('#addPersonal').onclick=()=>personalModal();document.querySelectorAll('[data-sub]').forEach(x=>x.onclick=()=>{drill=x.dataset.sub;render()})}
function debts(){shell(`<div class="section-head"><h2>Dividas</h2><button class="btn primary" id="addDebt">Nova divida</button></div><div class="grid">${data.debts.map(d=>`<article class="card"><div class="muted">${d.direction==='receive'?'Tenho a receber':'Tenho a pagar'}</div><h3>${esc(d.person)}</h3><div class="money ${d.direction==='receive'?'blue':'red'}">${kz(d.total-d.paid)}</div><div class="row-actions"><button class="btn warn" data-pay-debt="${d.id}">Registar pagamento</button><button class="btn danger" data-del-debt="${d.id}">Eliminar</button></div></article>`).join('')||empty('Sem dividas registadas.')}</div>`);document.querySelector('#addDebt').onclick=debtModal;document.querySelectorAll('[data-del-debt]').forEach(x=>x.onclick=()=>{data.debts=data.debts.filter(d=>d.id!==x.dataset.delDebt);save()});document.querySelectorAll('[data-pay-debt]').forEach(x=>x.onclick=()=>payDebt(x.dataset.payDebt))}
function third(){if(drill){const p=data.people.find(x=>x.id===drill),moves=data.moves.filter(m=>m.owner==='third'&&m.personId===drill);shell(`<button class="btn dark" id="back">Voltar</button><section class="hero"><div>Conta de ${esc(p?.name||'')}</div><div class="two"><div><small>Disponivel</small><div class="big">${kz(thirdBalance(drill))}</div></div><div><small>A receber</small><div class="big" style="color:#fde68a">${kz(loanDue(drill))}</div></div></div></section><div class="section-head"><h2>Historico</h2><button class="btn primary" id="addThird">Movimento</button></div>${movementList(moves,true)}`);document.querySelector('#back').onclick=()=>{drill=null;render()};document.querySelector('#addThird').onclick=()=>thirdModal(drill);bindRows();return}shell(`<div class="section-head"><h2>Dinheiro de outrem</h2><button class="btn primary" id="addPerson">Adicionar pessoa</button></div><div class="grid">${data.people.map(p=>`<article class="card click" data-person="${p.id}"><h3>${esc(p.name)}</h3><div class="muted">${esc(p.note||'')}</div><div class="two"><div><div class="muted">Disponivel</div><div class="money green">${kz(thirdBalance(p.id))}</div></div><div><div class="muted">A receber</div><div class="money amber">${kz(loanDue(p.id))}</div></div></div></article>`).join('')||empty('Adicione uma pessoa.')}</div>`);document.querySelector('#addPerson').onclick=personModal;document.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>{drill=x.dataset.person;render()})}
function locations(){if(drill){const l=data.locations.find(x=>x.id===drill),rows=[{name:'Meu dinheiro',amount:personalMoves().filter(m=>m.locationId===drill).reduce((s,m)=>s+signed(m),0)},...data.people.map(p=>({name:p.name,amount:data.moves.filter(m=>m.owner==='third'&&m.personId===p.id&&m.locationId===drill).reduce((s,m)=>s+signed(m),0)}))].filter(x=>x.amount!==0);shell(`<button class="btn dark" id="back">Voltar</button><section class="hero"><div>Total em ${esc(l?.name||'')}</div><div class="big">${kz(locationTotal(drill))}</div></section><div class="list">${rows.map(r=>`<div class="row"><div class="row-main"><strong>${esc(r.name)}</strong></div><div class="money blue">${kz(r.amount)}</div></div>`).join('')||empty('Nao existe dinheiro neste local.')}</div>`);document.querySelector('#back').onclick=()=>{drill=null;render()};return}shell(`<div class="section-head"><h2>Locais do dinheiro</h2><button class="btn primary" id="addLocation">Criar local</button></div><div class="grid">${data.locations.map(l=>`<article class="card"><div class="muted">${esc(l.type)}</div><h3>${esc(l.name)}</h3><div class="money blue">${kz(locationTotal(l.id))}</div><div class="row-actions"><button class="btn soft" data-location="${l.id}">Ver distribuicao</button><button class="btn danger" data-del-location="${l.id}">Eliminar</button></div></article>`).join('')||empty('Crie o primeiro local.')}</div>`);document.querySelector('#addLocation').onclick=locationModal;document.querySelectorAll('[data-location]').forEach(x=>x.onclick=()=>{drill=x.dataset.location;render()});document.querySelectorAll('[data-del-location]').forEach(x=>x.onclick=()=>deleteLocation(x.dataset.delLocation))}
function movementList(items,loans=false){return `<div class="list">${items.map(m=>`<div class="row"><div class="row-main"><strong>${esc(m.desc)}</strong><span class="muted">${esc(locName(m.locationId))} · ${m.date}${m.type==='loan'?` · Para ${esc(m.borrower)} · Pendente ${kz(m.amount-(m.received||0))}`:''}</span></div><div class="${m.type==='in'?'green':m.type==='loan'?'amber':'red'}"><b>${m.type==='in'?'+':'-'}${kz(m.amount)}</b></div><div class="row-actions">${loans&&m.type==='loan'&&m.amount>(m.received||0)?`<button class="btn warn" data-repay="${m.id}">Receber</button>`:''}<button class="btn danger" data-del-move="${m.id}">Eliminar</button></div></div>`).join('')||empty('Sem movimentos.')}</div>`}
function bindRows(){document.querySelectorAll('[data-del-move]').forEach(x=>x.onclick=()=>{const mid=x.dataset.delMove;data.moves=data.moves.filter(m=>m.id!==mid&&m.loanId!==mid);save()});document.querySelectorAll('[data-repay]').forEach(x=>x.onclick=()=>repaymentModal(x.dataset.repay))}
function modal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg"><div class="modal"><div class="modal-head"><strong>${title}</strong><button class="btn" id="closeModal">X</button></div><div class="modal-body">${body}</div></div></div>`);document.querySelector('#closeModal').onclick=closeModal}
function closeModal(){document.querySelector('.modal-bg')?.remove()}
const field=(l,n,type='text',extra='')=>`<div class="field"><label>${l}</label><input name="${n}" type="${type}" ${extra}></div>`;
const select=(l,n,opts)=>`<div class="field"><label>${l}</label><select name="${n}" required>${opts}</select></div>`;
const locationOptions=()=>`<option value="">Selecione</option>`+data.locations.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('');
function locationModal(){modal('Criar local',`<form id="f">${field('Nome','name','text','required placeholder="Ex.: BFA, Cofre, Em mao"')}${select('Tipo','type','<option>Banco</option><option>Numerario</option><option>Carteira digital</option><option>Outro</option>')}<button class="btn primary">Criar</button></form>`);document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.locations.push({id:id(),name:f.get('name'),type:f.get('type')});closeModal();save()}}
function subModal(){modal('Nova subconta',`<form id="f">${field('Nome','name','text','required placeholder="Ex.: Formacao"')}${field('Finalidade','note')}<button class="btn primary">Criar</button></form>`);document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.subs.push({id:id(),name:f.get('name'),note:f.get('note')});closeModal();save()}}
function personModal(){modal('Adicionar pessoa',`<form id="f">${field('Nome','name','text','required')}${field('Observacao','note')}<button class="btn primary">Criar</button></form>`);document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.people.push({id:id(),name:f.get('name'),note:f.get('note')});closeModal();save()}}
function personalModal(defaultSub=''){modal('Movimento pessoal',`<form id="f">${select('Subconta','subId','<option value="">Selecione</option>'+data.subs.map(s=>`<option value="${s.id}" ${s.id===defaultSub?'selected':''}>${esc(s.name)}</option>`).join(''))}${select('Tipo','type','<option value="in">Entrada</option><option value="out">Saida</option>')}${field('Descricao','desc','text','required')}${field('Valor','amount','number','min="1" required')}${field('Data','date','date',`value="${new Date().toISOString().slice(0,10)}" required`)}${select('Local','locationId',locationOptions())}<button class="btn primary">Guardar</button></form>`);document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),m={id:id(),owner:'personal',subId:f.get('subId'),type:f.get('type'),amount:Number(f.get('amount')),date:f.get('date'),desc:f.get('desc'),locationId:f.get('locationId')};if(m.type==='out'&&m.amount>subBalance(m.subId))return alert('Saldo insuficiente nesta subconta.');data.moves.unshift(m);closeModal();save()}}
function debtModal(){modal('Nova divida',`<form id="f">${select('Situacao','direction','<option value="receive">Tenho a receber</option><option value="pay">Tenho a pagar</option>')}${field('Pessoa ou entidade','person','text','required')}${field('Valor total','total','number','min="1" required')}${field('Ja pago','paid','number','value="0" min="0"')}${field('Vencimento','due','date','required')}<button class="btn primary">Guardar</button></form>`);document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.debts.unshift({id:id(),direction:f.get('direction'),person:f.get('person'),total:Number(f.get('total')),paid:Number(f.get('paid')),due:f.get('due')});closeModal();save()}}
function thirdModal(personId){modal('Movimento de terceiro',`<form id="f">${select('Tipo','type','<option value="in">Entrada</option><option value="out">Saida definitiva</option><option value="loan">Emprestimo a receber</option>')}${field('Descricao','desc','text','required')}${field('Valor','amount','number','min="1" required')}${field('Data','date','date',`value="${new Date().toISOString().slice(0,10)}" required`)}<div id="loanFields" class="hidden"><div class="notice">Escolha pessoa cadastrada ou externa.</div>${select('Tipo de pessoa','borrowerType','<option value="internal">Cadastrada</option><option value="external">Externa</option>')}<div id="borrowerBox"></div>${field('Data de devolucao','dueDate','date')}</div>${select('Local','locationId',locationOptions())}<button class="btn primary">Guardar</button></form>`);const form=document.querySelector('#f'),type=form.elements.type,kind=form.elements.borrowerType,box=document.querySelector('#borrowerBox');const refresh=()=>{document.querySelector('#loanFields').classList.toggle('hidden',type.value!=='loan');box.innerHTML=kind.value==='internal'?select('Pessoa cadastrada','borrowerId','<option value="">Selecione</option>'+data.people.filter(p=>p.id!==personId).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')):field('Nome da pessoa externa','borrowerName','text','required')};type.onchange=refresh;kind.onchange=refresh;refresh();form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),m={id:id(),owner:'third',personId,type:f.get('type'),amount:Number(f.get('amount')),date:f.get('date'),desc:f.get('desc'),locationId:f.get('locationId')};if((m.type==='out'||m.type==='loan')&&m.amount>thirdBalance(personId))return alert('Saldo insuficiente.');if(m.type==='loan'){m.borrowerType=f.get('borrowerType');m.borrower=m.borrowerType==='internal'?data.people.find(p=>p.id===f.get('borrowerId'))?.name:f.get('borrowerName');m.dueDate=f.get('dueDate');m.received=0}data.moves.unshift(m);closeModal();save()}}
function repaymentModal(mid){const loan=data.moves.find(m=>m.id===mid),pending=loan.amount-(loan.received||0);modal(`Pagamento de ${esc(loan.borrower)}`,`<form id="f"><div class="notice">Pendente: <b>${kz(pending)}</b></div>${field('Valor recebido','amount','number',`min="1" max="${pending}" required`)}${field('Data','date','date',`value="${new Date().toISOString().slice(0,10)}" required`)}${select('Onde entrou?','locationId',locationOptions())}<button class="btn primary">Confirmar</button></form>`);document.querySelector('#f').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),a=Number(f.get('amount'));if(a>pending)return;loan.received=(loan.received||0)+a;data.moves.unshift({id:id(),owner:'third',personId:loan.personId,type:'in',amount:a,date:f.get('date'),desc:`Pagamento recebido de ${loan.borrower}`,locationId:f.get('locationId'),loanId:loan.id});closeModal();save()}}
function payDebt(did){const d=data.debts.find(x=>x.id===did),p=d.total-d.paid,a=Number(prompt(`Valor do pagamento. Pendente: ${kz(p)}`));if(a>0&&a<=p){d.paid+=a;save()}}
function deleteLocation(lid){if(data.moves.some(m=>m.locationId===lid))return alert('Este local tem movimentos e nao pode ser eliminado.');data.locations=data.locations.filter(l=>l.id!==lid);save()}
function empty(t){return `<div class="empty">${t}</div>`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function bindGlobal(){document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{view=x.dataset.nav;drill=null;render()});document.querySelector('#exportBtn').onclick=exportBackup;document.querySelector('#importFile').onchange=importBackup;const b=document.querySelector('#installBtn');b.onclick=installApp;b.style.display=deferredPrompt?'inline-block':'none'}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`meu-controlo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importBackup(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!parsed.data)throw Error();if(confirm('Substituir os dados atuais pelo backup?')){data=parsed.data;save()}}catch{alert('Backup invalido.')}};r.readAsText(file)}
async function installApp(){if(!deferredPrompt)return alert('Use o menu do navegador e escolha Instalar aplicacao.');deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;render()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;render()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
